language: python
sudo: false

python:
  - "3.5"
  - "3.4"
  - "2.7"

env:
  - DJANGO="django==1.8.14"
  - DJANGO="django==1.9.8"
  - DJANGO="django==1.10.5"
  - DJANGO="django==1.11b1"

install:
  - pip install $DJANGO jinja2 "django-pipeline<1.6" pytz mock

script:
  - cd testing && python runtests.py

notifications:
  email:
    recipients:
      - niwi@niwi.nz
    on_success: change
    on_failure: change
